---
title: "Snowcover vignette for PI Charter"
author: "Mike Verhoeven"
date: "`r Sys.Date()`"
output: html_document
---

#To-do: 
1. Drop multiple per year obs via taking max CLP


# Prep WS
```{r}
#load libraries
library(data.table)
library(tidyr)
library(stringr)
library(ggplot2)
library(plotly)


#import Data
surveys <- fread("scripts&data/data/input/lake_year_data.csv")
rawdata <- fread("scripts&data/data/input/PCRIsurveysPICharter2srt_sheet1rawdata.csv")
  
```


#data explore
```{r}
#see if we can re-generate ray's calc'd CLP values
# summary(rawdata)
  rawdata[ , .N , .(SURVEY_START, DOW) ]
  names(rawdata)[str_detect(names(rawdata), "pota")]
  
#alltime max vet depth 
  
  a <- rawdata[ , .("survey_ident"= .GRP, "totnsamp" = .N, "clpN" = sum(potamogeton_crispus >= 1, na.rm = T), "lat_median" = median(latitude, na.rm = T), "lon_median" = median(longitude, na.rm = T)) ,   , .(SURVEY_START, DOW) ][ , clpfoc := clpN/totnsamp ,]
  
  
  #get snow data https://www.dnr.state.mn.us/climate/historical/acis_stn_data_monthly_table.html?sid=mspthr&sname=Twin%20Cities%20Area&sdate=1884-07-01&edate=por&element=snow&span=season&counts=no
snow <- fread("scripts&data/data/input/MSP_area_snow.csv")
  snow
  
#convert to cm
  snow[ , names(.SD) := lapply(.SD, function(x){x*2.54}), .SDcols = !c("Winter_end_year")]

#add snow to plant abund data:
  a[ , date := as.IDate(SURVEY_START, format = "%m/%d/%Y") , ]
  a[ , year := year(date) , ]
  
  
  a[snow, on = .(year = Winter_end_year ) , annual_snowfall := ANN]

  a[ DOW %in% a[ ,.N , DOW][N>2, DOW], .N ,  DOW]
  
  a[ , county := substr(str_pad(as.character(DOW),pad = "0", side = "left", width = 8), start = 1, stop = 2) , ]
  
  all_state <- a
  rm(a)
  
  metro <- all_state[ county %in% c("02", "27", "19", "62", "82", "10" ,"70")  ]

metro[ ,.N , DOW][N>2, DOW]
  
metro[ DOW %in% metro[ ,.N , DOW][N>2, DOW] , hist(year) ]


metro[ , length(unique(year(date))) , DOW ]

metro[ , length(unique(year(date))) , DOW ][ , summary(V1) , ]

metro[ ,summary(year(date)) , ]

ggplot(metro[DOW %in% metro[year > 2015 ,.N , DOW][N>2, DOW] & year > 2015, , ] , aes( annual_snowfall, clpfoc), )+
   geom_point()+
   geom_smooth(method = "lm")+
   facet_wrap(~DOW, scales = "free")

summary(lm(clpfoc~annual_snowfall, data = metro[DOW %in% metro[,.N , DOW][N>2, DOW], , ]))


plotpanels <- ggplot(metro[DOW %in% metro[ ,.N , DOW][N>2, DOW], , ], aes( annual_snowfall, clpfoc, group = as.factor(DOW)) )+
  geom_point(aes(color = as.factor(DOW)))+
  geom_smooth(aes(color = as.factor(DOW)), method = "lm", se = F)

ggplotly(plotpanels)

```

So, from that plot I'd say the answer is no, a lake manager can't just use the MSP snowcover to assess effects on CLP.


To do list: 
- exclude non 7co metro -DONE
- run before 2016 - DONE
- 

# Figure for Vignette
```{r}
# make a background of "all data"

ggplot(metro , aes( annual_snowfall, clpfoc), )+
   geom_point()

ggplot(metro, aes( annual_snowfall, clpfoc) )+
  # geom_point(aes(color = as.factor(DOW)), alpha =.5)+
  stat_smooth(geom='line', method = "lm" ,alpha=0.25, se = FALSE, aes(color = as.factor(DOW)), linewidth = 1.0)+
  theme_bw()+
  guides(color="none")+
  geom_smooth(method = "lm", linewidth = 1.5)+
    scale_y_continuous(name="Curlyleaf pondweed Abundance") +
  scale_x_continuous(name="Annual Snowfall in Region (cm)")+ 
  theme(axis.text = element_text( size=10),
    axis.title.x = element_text(face="bold", size=15),
        axis.title.y  = element_text(face = "bold", size=15))

summary(lm(clpfoc~annual_snowfall, data = metro)) # the unfiltered 
summary(lm(clpfoc~annual_snowfall, data = metro[DOW %in% metro[year < 2016 ,.N , DOW][ ,DOW], , ]))
summary(lm(clpfoc~annual_snowfall, data = metro[DOW %in% metro[year > 2015 ,.N , DOW][ ,DOW], , ]))

```

```{r}
# For multiple occ ests per year
metro[ , .N , .(DOW, year(date)) ][ ,hist(N) ,]
setorder(metro,-clpfoc) #order dt by increasing CLP
metro[ , ann_abund_rank := 1:.N   ,  .(DOW, year) ] # tag ranked order of abunds within year

metro_annmax <- metro[ann_abund_rank==1, , ]

plotpanels <- ggplot(metro_annmax[DOW %in% metro_annmax[ ,.N , DOW][N>2, DOW], , ], aes( annual_snowfall, clpfoc, group = as.factor(DOW)) )+
  geom_point(aes(color = as.factor(DOW)))+
  geom_smooth(aes(color = as.factor(DOW)), method = "lm", se = F)

ggplotly(plotpanels)

# make a background of "all data"

ggplot(metro_annmax , aes( annual_snowfall, clpfoc), )+
   geom_point()

ggplot(metro_annmax, aes( annual_snowfall, clpfoc) )+
  # geom_point(aes(color = as.factor(DOW)), alpha =.5)+
  stat_smooth(geom='line', method = "lm" ,alpha=0.25, se = FALSE, aes(color = as.factor(DOW)), linewidth = 1.0)+
  theme_bw()+
  guides(color="none")+
  geom_smooth(method = "lm", linewidth = 1.5)+
    scale_y_continuous(name="Curlyleaf pondweed Abundance") +
  scale_x_continuous(name="Annual Snowfall in Region (cm)")+ 
  theme(axis.text = element_text( size=10),
    axis.title.x = element_text(face="bold", size=15),
        axis.title.y  = element_text(face = "bold", size=15))

summary(lm(clpfoc~annual_snowfall, data = metro_annmax)) # the unfiltered 
summary(lm(clpfoc~annual_snowfall, data = metro_annmax[DOW %in% metro_annmax[year < 2016 ,.N , DOW][ ,DOW], , ]))
summary(lm(clpfoc~annual_snowfall, data = metro_annmax[DOW %in% metro_annmax[year > 2015 ,.N , DOW][ ,DOW], , ]))


#generate a lake specific R2 and p val
lake_ests <- data.table(DOW = metro_annmax[ , .N , DOW][N>2, DOW])
for (i in metro_annmax[ , .N , DOW][N>2, DOW]) {
  # i = 27002800
  #snow slope
  lake_iter <- lm(
    clpfoc~annual_snowfall, data = metro_annmax[DOW == i]
  ) 
  lake_ests[ DOW == i, snow_slope :=  summary(lake_iter)$coefficients[2,1] ]
  #snow_p
  lake_ests[ DOW == i, snow_pval :=  summary(lake_iter)$coefficients[2,4] ]
  # R-squared
  lake_ests[ DOW == i, snow_Rsq :=  summary(lake_iter)$r.squared ]
  #mean_clp
  lake_ests[ DOW == i, mean_clp :=  metro_annmax[DOW == i, mean(clpfoc) , ] ]  
  
  
}

ggplot(lake_ests, aes(snow_slope) )+
  geom_histogram( aes(fill = snow_Rsq))


ggplot(lake_ests, aes(snow_slope, snow_Rsq) )+
  geom_point()
ggplot(lake_ests, aes(snow_slope, snow_pval) )+
  geom_point( )


lake_ests[snow_Rsq>.5 ][order(snow_slope)]


lake_ests[snow_pval < 0.05 & 
            snow_slope < 0, ]

metro_slopes <- metro_annmax[lake_ests, on = .(DOW)]


```

So, from that plot I'd say the answer is no, a lake manager can't just use the MSP snowcover to assess effects on CLP. 






